kind: Deployment
apiVersion: apps/v1
metadata:
  name: kandula-pod
  labels:
    app: kandula
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kandula
  template:
    metadata:
      labels:
        app: kandula
    spec:
      containers:
        - image: lihilure/kandula_image_app:TAG
          name: kandula
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          env:
            - name: FLASK_ENV
              value: development
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          envFrom:
            - secretRef:
                name: mysecret

