# Create a pod and expose port 8080
apiVersion: v1
kind: Pod
metadata:
  name: kandula-pod
  labels:
    app: backend
spec:
   containers:
     - image: lihilure/kandula_image_app:v1
       name: kandula
       ports:
         - containerPort: 5000
           name: http
           protocol: TCP
       env:
         - name: FLASK_ENV
           value: development
         - name: AWS_DEFAULT_REGION
           value: us-east-1
       envFrom:
         - secretRef:
              name: mysecret

---
 apiVersion: v1
 kind: Service
 metadata:
   name: backend-service
   annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "6f84ea13-9b72-4b4f-ab8e-e41469f4468e"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "kandula.ops.club"
    service.beta.kubernetes.io/do-loadbalancer-http2-ports: 443,80
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:314452776120:certificate/6f84ea13-9b72-4b4f-ab8e-e41469f4468e
 spec:
   selector:
     app: backend
   type: LoadBalancer
   ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000