# Create a pod and expose port 8080
apiVersion: v1
kind: Pod
metadata:
  name: kandula-pod
  labels:
    app: kandula
spec:
   containers:
     - image: lihilure/kandula_image_app:TAG
       name: kandula
       ports:
         - containerPort: 5000
           name: http
           protocol: TCP
         - containerPort: 9100
           name: metrics
           protocol: TCP
       env:
         - name: FLASK_ENV
           value: development
         - name: AWS_DEFAULT_REGION
           value: us-east-1
       envFrom:
         - secretRef:
              name: mysecret
